name : Docker cicd to ecr and ecs
on:
  push: 
    branches : master
    
  workflow_dispatch:

jobs:
   build-push-deploy:
    runs-on : ubuntu-latest
    
    steps:
      - name : checkout code
        uses : actions/checkout@v5        
     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

  
      - name: Build Docker image
        run: |
          docker build -t webpageimage:latest .


      - name: Tag Docker image
        run: |
          docker tag webpageimage:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/webpageimage:latest


      - name: Push Docker image to ECR
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/webpageimage:latest


      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster nginx-cluster \
            --service nginx-service \
            --force-new-deployment
    
  
